- hosts: nginx
  become: true
  roles:
    - nginx
    - filebeat

- hosts: prometheus
  become: true
  roles:
    - prometheus

- hosts: grafana
  become: true
  roles:
    - grafana

- hosts: elasticsearch
  become: true
  roles:
    - elasticsearch

- hosts: kibana
  become: true
  roles:
    - kibana